export enum PagesTypes {
  OVERVIEW_PAGE = "OVERVIEW_PAGE",
  ITEMS_PAGE = "ITEMS_PAGE",
  EMPLOYEES_PAGE = "EMPLOYEES_PAGE",
  DEMAND_PAGE = "DEMAND_PAGE",
  RECOMMENDATIONS_PAGE = "RECOMMENDATIONS_PAGE",
}
