export enum PagesTypes {
  OVERVIEW_PAGE = "OVERVIEW_PAGE",
  ITEMS_PAGE = "ITEMS_PAGE",
  CATEGORY_PAGE = "CATEGORY_PAGE",
  PURCHASES_PAGE = "PURCHASES_PAGE",
  SALES_PAGE = "SALES_PAGE",
  ADMINISTRATIVE_PURCHASES = "ADMINISTRATIVE_PURCHASES",
  EMPLOYEES_PAGE = "EMPLOYEES_PAGE",
  RECOMMENDATIONS_PAGE = "RECOMMENDATIONS_PAGE",
}
